name: Azure Storage Scripts CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/cli@v1

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Run vault creation script
        run: |
          chmod +x ./vaultcreationscript.sh
          ./vaultcreationscript.sh

      - name: Run file manager script 
        run: |
          chmod +x ./filemanager.sh
          
          touch testfile.txt
          ./filemanager.sh upload testfile.txt testblob

      - name: Upload logs as artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: script-logs
          path: |
            filemanager.log
